/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MangaStatus = IDL.Variant({
  'OnHold' : IDL.Null,
  'PlanToRead' : IDL.Null,
  'Reading' : IDL.Null,
  'Dropped' : IDL.Null,
  'Completed' : IDL.Null,
  'Incomplete' : IDL.Null,
});
export const MangaEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : MangaStatus,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'altTitle1' : IDL.Text,
  'altTitle2' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'synopsis' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
  'rating' : IDL.Opt(IDL.Nat),
  'totalChapters' : IDL.Opt(IDL.Nat),
  'isFavourite' : IDL.Bool,
  'currentChapter' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MangaStatus,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [MangaEntry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEntry' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(MangaEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFavourite' : IDL.Func([IDL.Text], [MangaEntry], []),
  'updateChapters' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
      [MangaEntry],
      [],
    ),
  'updateEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MangaStatus,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [MangaEntry],
      [],
    ),
  'updateRating' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [MangaEntry], []),
  'updateStatus' : IDL.Func([IDL.Text, MangaStatus], [MangaEntry], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MangaStatus = IDL.Variant({
    'OnHold' : IDL.Null,
    'PlanToRead' : IDL.Null,
    'Reading' : IDL.Null,
    'Dropped' : IDL.Null,
    'Completed' : IDL.Null,
    'Incomplete' : IDL.Null,
  });
  const MangaEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : MangaStatus,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'altTitle1' : IDL.Text,
    'altTitle2' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'synopsis' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
    'rating' : IDL.Opt(IDL.Nat),
    'totalChapters' : IDL.Opt(IDL.Nat),
    'isFavourite' : IDL.Bool,
    'currentChapter' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MangaStatus,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [MangaEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEntry' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(MangaEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFavourite' : IDL.Func([IDL.Text], [MangaEntry], []),
    'updateChapters' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat)],
        [MangaEntry],
        [],
      ),
    'updateEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MangaStatus,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [MangaEntry],
        [],
      ),
    'updateRating' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [MangaEntry], []),
    'updateStatus' : IDL.Func([IDL.Text, MangaStatus], [MangaEntry], []),
  });
};

export const init = ({ IDL }) => { return []; };