/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Int = bigint;
export interface MangaEntry {
  'id' : string,
  'cenLvl' : [] | [number],
  'status' : MangaStatus,
  'coverImageUrl' : [] | [string],
  'title' : string,
  'artRating' : [] | [number],
  'altTitle1' : string,
  'altTitle2' : string,
  'createdAt' : Int,
  'updatedAt' : Int,
  'synopsis' : string,
  'genres' : Array<string>,
  'notes' : string,
  'rating' : [] | [bigint],
  'totalChapters' : [] | [bigint],
  'isFavourite' : boolean,
  'currentChapter' : bigint,
}
export type MangaStatus = { 'OnHold' : null } |
  { 'PlanToRead' : null } |
  { 'Reading' : null } |
  { 'Dropped' : null } |
  { 'Completed' : null } |
  { 'Incomplete' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEntry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      MangaStatus,
      bigint,
      [] | [bigint],
      [] | [bigint],
      [] | [number],
      [] | [number],
      [] | [string],
      string,
      Array<string>,
      boolean,
    ],
    MangaEntry
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEntry' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntries' : ActorMethod<[], Array<MangaEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCaller' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleFavourite' : ActorMethod<[string], MangaEntry>,
  'updateArtRating' : ActorMethod<[string, [] | [number]], MangaEntry>,
  'updateCenLvl' : ActorMethod<[string, [] | [number]], MangaEntry>,
  'updateChapters' : ActorMethod<[string, bigint, [] | [bigint]], MangaEntry>,
  'updateEntry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      MangaStatus,
      bigint,
      [] | [bigint],
      [] | [bigint],
      [] | [number],
      [] | [number],
      [] | [string],
      string,
      Array<string>,
      boolean,
    ],
    MangaEntry
  >,
  'updateRating' : ActorMethod<[string, [] | [bigint]], MangaEntry>,
  'updateStatus' : ActorMethod<[string, MangaStatus], MangaEntry>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];